/** Auto-generated catalog of SU official blanks. Do not edit by hand — regenerate via scripts if inventory changes. */

export type HubId =
  | "training"
  | "phd"
  | "career"
  | "load"
  | "contracts"
  | "mywork"
  | "letters"
  | "other";

export const HUBS: { id: HubId; titleBg: string; titleEn: string; blurbBg: string; blurbEn: string }[] = [
  { id: "training", titleBg: "Обучение", titleEn: "Studies", blurbBg: "Студентски заявления, договори за обучение, дубликати и помощи.", blurbEn: "Student petitions, study contracts, diploma copies and aid." },
  { id: "phd", titleBg: "Докторантура", titleEn: "Doctoral", blurbBg: "Зачисляване, журита, договори и изплащания по докторантура.", blurbEn: "Enrolment, juries, contracts and doctoral payments." },
  { id: "career", titleBg: "Академична кариера", titleEn: "Academic career", blurbBg: "Конкурси за академични длъжности и декларации на жури.", blurbEn: "Academic-position competitions and jury declarations." },
  { id: "load", titleBg: "Натовареност и хонорари", titleEn: "Load and honoraria", blurbBg: "Натовареност, хонорари, норматив, базови учители, план-сметка.", blurbEn: "Load, honoraria, over-norm, base teachers, master's budget." },
  { id: "contracts", titleBg: "Договори и проекти", titleEn: "Contracts and projects", blurbBg: "Граждански договори, проекти, гости, извънреден труд, публикации.", blurbEn: "Civil contracts, projects, guests, overtime, publications." },
  { id: "mywork", titleBg: "Моя труд", titleEn: "My work", blurbBg: "Отпуск, назначаване, преназначаване, декларация при постъпване.", blurbEn: "Leave, hire, reassignment, incoming-employee declaration." },
  { id: "letters", titleBg: "Кореспонденция", titleEn: "Correspondence", blurbBg: "Официална кореспонденция — входящи/изходящи и докладна.", blurbEn: "Official correspondence — incoming/outgoing and memos." },
];

export type FieldType = "text" | "textarea" | "date" | "number" | "email" | "select" | "checkbox" | "iban" | "loadLines";

export type CatalogField = {
  name: string;
  labelBg: string;
  labelEn: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; labelBg: string; labelEn: string }[];
};

export type { RoutePhase, RouteStepDef } from "./processRoute";
export { routeFor, copyPackFor, mergeCaseRoute, parseRouteJson } from "./processRoute";

export type CatalogProcess = {
  slug: string;
  catalogCode: string | null;
  hub: HubId;
  family: string;
  wizardKind: "load-5-2" | "dynamic-load" | "dynamic";
  titleBg: string;
  titleEn: string;
  descriptionBg: string;
  descriptionEn: string;
  rolesAllowed: string;
  driveFileId: string;
  sourceFolder: string;
  originalTitle: string;
  mimeType: string;
  size: number;
  templateRel: string | null;
  nomenclatura: string | null;
  hasPayment: boolean;
  hasLegal: boolean;
};

export type HandbookItem = {
  slug: string;
  kind: string;
  titleBg: string;
  titleEn: string;
  summaryBg: string;
  summaryEn: string;
  driveFileId: string;
  sourceFolder: string;
  originalTitle: string;
  mimeType: string;
  size: number;
};

export const CATALOG: CatalogProcess[] = [
  {
    slug: "p-3-1",
    catalogCode: "3.1",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Заявление за дубликат на диплома",
    titleEn: "Diploma duplicate request",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "1Bg_blmQcMecHjJ_Boi5u-7IeGW2A3IWA",
    sourceFolder: "student documents",
    originalTitle: "Obrazec-3.1-Zayavlenie dublikat na diploma.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/student-documents/p-3-1.docx",
    nomenclatura: "УД-12",
    size: 19455,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-2",
    catalogCode: "3.2",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Заявление за обучение в нова специалност",
    titleEn: "Study a second / new specialty",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "16usagWIfrgue3uj9bTZPsCyF24S3HwH6",
    sourceFolder: "student documents",
    originalTitle: "Obrazec-3.2-Zayavlenie obuchenie nova-2018.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-2.doc",
    nomenclatura: "УД-12",
    size: 46080,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-2c",
    catalogCode: "3.2C",
    hub: "training",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор — бакалаври и магистри, нова специалност 2025/26",
    titleEn: "Contract — BA/MA new specialty 2025/26",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.2C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.2C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1-elrnmtp_qSjOFW3zIGEr-GEFodg8t3J",
    sourceFolder: "student documents",
    originalTitle: "Dogovor_za_bakalavri_i_magistri_nova_specialnost_2025_2026 (2).doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-2c.doc",
    nomenclatura: "УД-12",
    size: 57344,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-3-2m",
    catalogCode: "3.2M",
    hub: "training",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор за платено обучение — магистър 2025/26",
    titleEn: "Paid-study contract — master's 2025/26",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.2M. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.2M. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1yL9eaDBPDtPkemHMltWqPifrtk7bMc_g",
    sourceFolder: "student documents",
    originalTitle: "Dogovor_za_plateno_obuchenie_magistar_2025_2026.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-2m.doc",
    nomenclatura: "УД-12",
    size: 62976,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-3-3",
    catalogCode: "3.3",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Възстановяване на студентски права (Ректорат / ОД)",
    titleEn: "Restore student rights (Rectorate / Education dept.)",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.3. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.3. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "1lX8V-f-zZMc5bVL657QAlLz4HTz8eXf2",
    sourceFolder: "student documents",
    originalTitle: "Obrazec-3.3-Zayavlenie vastanoviavane studentski prava.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-3.doc",
    nomenclatura: "УД-12",
    size: 41472,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-4",
    catalogCode: "3.4",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Възстановяване на студентски права (факултет)",
    titleEn: "Restore student rights (faculty only)",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.4. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.4. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "1hEsPegOOlw__jtkQctaQPkRfv888832I",
    sourceFolder: "student documents",
    originalTitle: "Obrazec-3.4-Zayavlenie vastanoviavane studenti.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-4.doc",
    nomenclatura: "УД-12",
    size: 41984,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-5",
    catalogCode: "3.5",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Прекъсване на студентски права",
    titleEn: "Interrupt studies",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.5. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.5. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "1rR7pV9sreAFON65K0eUtjTLpeVbZ5kLl",
    sourceFolder: "student documents",
    originalTitle: "Obrazec-3.5-Zayavlenie prekasvane studentski prava.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/student-documents/p-3-5.docx",
    nomenclatura: "УД-12",
    size: 20433,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-6",
    catalogCode: "3.6",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Заявление за европейско приложение към диплома",
    titleEn: "European diploma supplement",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.6. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.6. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "1QYWgK-IdK2hcY5FFZtpRxDqhQb7MYhHZ",
    sourceFolder: "student documents",
    originalTitle: "Obrazec-3.6-zaiavlenie evropeisko prolojenie.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-6.doc",
    nomenclatura: "УД-12",
    size: 33280,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-7",
    catalogCode: "3.7",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Заявление за финансова помощ",
    titleEn: "Student financial aid",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.7. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.7. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "student",
    driveFileId: "1phSQqR6d_-07iTVDd5HadlmV9i-46MQn",
    sourceFolder: "student documents",
    originalTitle: "3.7. Zayavlenie-finansova-pomosht.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/student-documents/p-3-7.doc",
    nomenclatura: "УД-12",
    size: 36864,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-3-8",
    catalogCode: "3.8",
    hub: "training",
    family: "petition",
    wizardKind: "dynamic",
    titleBg: "Application form — чуждестранни студенти",
    titleEn: "Application form — international students",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.8. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.8. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "applicant,student,faculty_admin",
    driveFileId: "1LNUio4Wavl8HG2iSwK0umYzwSeoOdZb5",
    sourceFolder: "student documents",
    originalTitle: "Obrazec 3.8-APPLICATION FORM.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/student-documents/p-3-8.docx",
    nomenclatura: "УД-12",
    size: 40817,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-3-8c",
    catalogCode: "3.8C",
    hub: "training",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор за чуждестранни студенти 2025/26",
    titleEn: "Contract — international students 2025/26",
    descriptionBg: "Официална бланка от Drive (student documents). Каталожен код: 3.8C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (student documents). Catalog code: 3.8C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1a1xzVo-z9cKgTygypOwIPTFjNgCI4F2H",
    sourceFolder: "student documents",
    originalTitle: "Dogovor_za_chujdestranni_studenti_29-09-2025_2026.pdf",
    mimeType: "application/pdf",
    templateRel: "templates/official/student-documents/p-3-8c.pdf",
    nomenclatura: "УД-12",
    size: 177825,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-1",
    catalogCode: "4.1",
    hub: "phd",
    family: "phd",
    wizardKind: "dynamic",
    titleBg: "Зачисляване в докторантура",
    titleEn: "PhD enrolment",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "19QmU1WXVT-JEs_9xtSgGR64K4glulXcT",
    sourceFolder: "phd",
    originalTitle: "4.1-doklad za zachisliavane v doktarantura.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-1.doc",
    nomenclatura: "ДДСК-01",
    size: 65536,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-4-11a",
    catalogCode: "4.11A",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Стипендия по ПМС 90/2000 — чл. 7 ал. 5 т. 1",
    titleEn: "PMS 90/2000 stipend — art. 7(5)(1)",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.11A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.11A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1pSVXS28GGj22-7Sn_zf1lcdE9wcy4Bwm",
    sourceFolder: "phd",
    originalTitle: "обр. 4.11 A - заповед по чл. 7, ал. 5, т. 1 от ПМС 90 от 2000 г(1).doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-11a.doc",
    nomenclatura: "ДДСК-01",
    size: 37376,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-11b",
    catalogCode: "4.11B",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Стипендия по ПМС 90/2000 — чл. 7 ал. 5 т. 2",
    titleEn: "PMS 90/2000 stipend — art. 7(5)(2)",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.11B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.11B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "19yNiNxkR1VKTOxX_ikUr6AL5c-yzx0pT",
    sourceFolder: "phd",
    originalTitle: "обр. 4.11 B - заповед по чл. 7, ал. 5, т. 2 от ПМС 90 от 2000 г.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-11b.doc",
    nomenclatura: "ДДСК-01",
    size: 36864,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-12",
    catalogCode: "4.12",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Възнаграждение за рецензия на проект на дисертация",
    titleEn: "Fee for dissertation-project review",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.12. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.12. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "12IPMf_I1dahG2wZ4P5dkwm_YRkG3r8je",
    sourceFolder: "phd",
    originalTitle: "обр. 4.12 - заповед за изплащане на възнаграждение за изготвяне на рецензия на проект на дисертационен труд съгл.чл. 24, ал. 5 ПУРПНСЗАДСУ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-12.doc",
    nomenclatura: "ДДСК-01",
    size: 41984,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-2",
    catalogCode: "4.2",
    hub: "phd",
    family: "phd",
    wizardKind: "dynamic",
    titleBg: "Комисия за кандидат-докторантски изпит",
    titleEn: "Candidate-PhD exam commission",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1DfWQ-I_e0wfTJYXUNFf76_b0EKpTllbh",
    sourceFolder: "phd",
    originalTitle: "4.2-doklad i zapoved komisia kandidatdoktorantski izpit.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-2.doc",
    nomenclatura: "ДДСК-01",
    size: 44032,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-3a",
    catalogCode: "4.3A",
    hub: "phd",
    family: "phd",
    wizardKind: "dynamic",
    titleBg: "Научно жури — заварени докторанти",
    titleEn: "Scientific jury — incumbent doctoral students",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.3A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.3A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1P7tdTqsBKIkDdqrJzTL-yayOe1eSzLdg",
    sourceFolder: "phd",
    originalTitle: "4.3 A -Doklad i zapoved za juri Dokor_ za zavareni doktoranti.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-3a.doc",
    nomenclatura: "ДДСК-01",
    size: 52224,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-3b",
    catalogCode: "4.3B",
    hub: "phd",
    family: "phd",
    wizardKind: "dynamic",
    titleBg: "Научно жури — нови докторанти",
    titleEn: "Scientific jury — new doctoral students",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.3B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.3B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1LL8FRBhbRCTK_SLLNqkbQyWCV4m34Hpf",
    sourceFolder: "phd",
    originalTitle: "4.3 B-Doklad i zapoved za juri Dokor_ za novi doktoranti.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-3b.doc",
    nomenclatura: "ДДСК-01",
    size: 54272,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-3c",
    catalogCode: "4.3C",
    hub: "phd",
    family: "phd",
    wizardKind: "dynamic",
    titleBg: "Научно жури — доктор на науките (нови)",
    titleEn: "Scientific jury — Doctor of Sciences (new)",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.3C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.3C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "18Fm31mTPwo5_nZg1ax6_JqKC7zxfkeON",
    sourceFolder: "phd",
    originalTitle: "4.3 C-Doklad i zapoved za juri_DN_novi.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-3c.doc",
    nomenclatura: "ДДСК-01",
    size: 55808,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-4a",
    catalogCode: "4.4A",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Договор с външни членове на жури (СТАР)",
    titleEn: "Civil contract with external jury (legacy / STAR)",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.4A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.4A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1sL2UdEh2bC7eU76A2OQI_A2jUu3JU90f",
    sourceFolder: "phd",
    originalTitle: "4.4 А-доклад и договор-сключване на договори с външни-СТАР.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/phd/p-4-4a.docx",
    nomenclatura: "ДДСК-01",
    size: 34487,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-4b",
    catalogCode: "4.4B",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Договор с външни членове на жури (НОВ)",
    titleEn: "Civil contract with external jury (NEW)",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.4B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.4B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1Xbl6d9l2VPuZrpi-OsYwB48BS7XxVZed",
    sourceFolder: "phd",
    originalTitle: "4.4 В-доклад и договор-сключване на договори с външни-НОВ.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/phd/p-4-4b.docx",
    nomenclatura: "ДДСК-01",
    size: 34376,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-5",
    catalogCode: "4.5",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Изплащане на външни членове на жури",
    titleEn: "Pay external jury members",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.5. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.5. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1qDe1kW5WgiPw7e8VgV4kQ0QDxhyXkWQl",
    sourceFolder: "phd",
    originalTitle: "4.5 -доклад - изплащане външни.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/phd/p-4-5.docx",
    nomenclatura: "ДДСК-01",
    size: 25578,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-6",
    catalogCode: "4.6",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Изплащане на вътрешни членове на жури",
    titleEn: "Pay internal jury members",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.6. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.6. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1BZdZNkVRnPELhbPtiwjvejB3eZ3y-n7Y",
    sourceFolder: "phd",
    originalTitle: "4.6 доклад и заповед-изплащане вътрешни-научни степени.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-6.doc",
    nomenclatura: "ДДСК-01",
    size: 63488,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-7",
    catalogCode: "4.7",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Възнаграждение за научно ръководство",
    titleEn: "Supervisor fee",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.7. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.7. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1kITRsF6w9C1hX8pphJovuq-0fuONVkiO",
    sourceFolder: "phd",
    originalTitle: "4.7-doklad i zapoved za vaznagrajdenie nauchno rakovodstvo-new.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/phd/p-4-7.docx",
    nomenclatura: "ДДСК-01",
    size: 25113,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-8",
    catalogCode: "4.8",
    hub: "phd",
    family: "pay",
    wizardKind: "dynamic",
    titleBg: "Изплащане за кандидат-докторантски изпит",
    titleEn: "Pay for candidate-PhD exam",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.8. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.8. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1-PEpd3TudmAog3kAyay_LNhwU_6Y_uFg",
    sourceFolder: "phd",
    originalTitle: "Obrazec-4.8-doklad i zapoved za izplachtene vaznagrajdenia kandidat doktoranti.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-8.doc",
    nomenclatura: "ДДСК-01",
    size: 53248,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-4-9-1",
    catalogCode: "4.9.1",
    hub: "phd",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация за конфликт на интереси — член на жури (PhD)",
    titleEn: "Conflict-of-interest declaration — PhD jury member",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.9.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.9.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "11XiDACSeypT6ZHZxs-oAnDO38c1HIiw-",
    sourceFolder: "phd",
    originalTitle: "4.9.1. Deklaracia_konflikt interesi_chlen juri.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/phd/p-4-9-1.docx",
    nomenclatura: "ДДСК-01",
    size: 25191,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-9-2",
    catalogCode: "4.9.2",
    hub: "phd",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация за мин. нац. изисквания — член на жури (PhD)",
    titleEn: "Min. national requirements — PhD jury member",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.9.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.9.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "10wPdkLQF5hcDbsHMzUw80LKRRcE-P_uk",
    sourceFolder: "phd",
    originalTitle: "4.9.2 декларация-мин.нац. изискв._член жури_PhD.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/phd/p-4-9-2.docx",
    nomenclatura: "ДДСК-01",
    size: 14942,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-4-d",
    catalogCode: "4.D",
    hub: "phd",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация (докторантура)",
    titleEn: "Declaration (doctoral)",
    descriptionBg: "Официална бланка от Drive (phd). Каталожен код: 4.D. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (phd). Catalog code: 4.D. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "187yLgdNGxoL-065rleUOdCk15Ks083vG",
    sourceFolder: "phd",
    originalTitle: "ДЕКЛАРАЦИЯ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/phd/p-4-d.doc",
    nomenclatura: "ДДСК-01",
    size: 27648,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-2-1",
    catalogCode: "2.1",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Обявяване на конкурс за академична длъжност",
    titleEn: "Announce academic-position competition",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1KX-j-5b2huZC2F9d6cuIDcBSEToMGIsM",
    sourceFolder: "documents",
    originalTitle: "Obrazec-2.1-doklad za obiaviavane na konkursi.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-1.docx",
    nomenclatura: "ЧР-09",
    size: 19833,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-1a",
    catalogCode: "2.1A",
    hub: "career",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Образец 2.1.А — справка натовареност (щатни + хонорувани)",
    titleEn: "Form 2.1.A — load spreadsheet (staff + honorary)",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.1A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.1A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1KAG4GEunL1jGDQ1BLHXX34Dm3PIo1IuK",
    sourceFolder: "documents",
    originalTitle: "Образец 2.1.А.xls",
    mimeType: "application/vnd.ms-excel",
    templateRel: "templates/official/documents/p-2-1a.xls",
    nomenclatura: "ЧР-09",
    size: 30208,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-2-2",
    catalogCode: "2.2",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Допускане на кандидати — асистент",
    titleEn: "Admit candidates — assistant",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1Bf12xJPmwF3yWYlGZp4jhoDJdmZ05SWF",
    sourceFolder: "documents",
    originalTitle: "Образец 2.2.-доклад и заповед_комисия по допускане_асистент.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-2.docx",
    nomenclatura: "ЧР-09",
    size: 22366,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-3",
    catalogCode: "2.3",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Допускане на кандидати — гл. ас. / доц. / проф.",
    titleEn: "Admit candidates — chief asst. / assoc. / prof.",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.3. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.3. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1LSLb5yjmBPpzfdhH1ML5fEAlhgLUkJTa",
    sourceFolder: "documents",
    originalTitle: "Образец 2.3.-доклад и заповед_комисия по допускане_ гл. ас._доц_проф.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-3.docx",
    nomenclatura: "ЧР-09",
    size: 21511,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-4",
    catalogCode: "2.4",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Комисия по провеждане на конкурс — асистент",
    titleEn: "Competition commission — assistant",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.4. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.4. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1S2qWwxT5rfF7lSCaQdH0Dms82KVio0jS",
    sourceFolder: "documents",
    originalTitle: "Образец 2.4.-доклад и заповед_комисия по провеждане _асистент.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-4.docx",
    nomenclatura: "ЧР-09",
    size: 23040,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-5",
    catalogCode: "2.5",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Научно жури — главен асистент",
    titleEn: "Scientific jury — chief assistant",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.5. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.5. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1noDQtqZPaqxdclOiqQVWrkVtQRtc-na-",
    sourceFolder: "documents",
    originalTitle: "Obrazec-2.5-doklad i zapoved nauchno juri za glaven asistent-new.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-5.docx",
    nomenclatura: "ЧР-09",
    size: 21776,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-5-1",
    catalogCode: "2.5.1",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Предложение за научно жури от катедрата — гл. асистент",
    titleEn: "Department proposal for jury — chief assistant",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.5.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.5.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1cPJvAAHKPIoDp1N9yt99AbB84MEgk5eH",
    sourceFolder: "documents",
    originalTitle: "Образец 2.5.1 доклад-предложение за НЖ от катедрата за провеждане на конкурс за главен асистент.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/documents/p-2-5-1.doc",
    nomenclatura: "ЧР-09",
    size: 32256,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-5-2",
    catalogCode: "2.5.2",
    hub: "career",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация за конфликт на интереси — конкурс гл. асистент",
    titleEn: "Conflict-of-interest declaration — chief assistant contest",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.5.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.5.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "1BsatbJFVHYfOm-VzwBZUf_NNixwtQQKM",
    sourceFolder: "documents",
    originalTitle: "Образец 2.5.2. декларация за конфликт на интереси- конкурс за главен асистент.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-5-2.docx",
    nomenclatura: "ЧР-09",
    size: 20311,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-5-3",
    catalogCode: "2.5.3",
    hub: "career",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация за мин. нац. изисквания — жури гл. асистент",
    titleEn: "Min. national requirements declaration — chief assistant jury",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.5.3. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.5.3. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "1tPFVK1plWAqcxR5FTsKRr-mQALMeYwDo",
    sourceFolder: "documents",
    originalTitle: "Образец 2.5.3. декларация за мин.нац. изискв. на членовете на НЖ_конкурс главен асистент.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-5-3.docx",
    nomenclatura: "ЧР-09",
    size: 17132,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-6",
    catalogCode: "2.6",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Научно жури — доцент / професор",
    titleEn: "Scientific jury — associate / professor",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.6. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.6. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1ofaqRcqIEORjQqyq1QgZhsTOB73ueaMp",
    sourceFolder: "documents",
    originalTitle: "Obrazec-2.6-doklad i zapovedi juri hablitirani-new.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-6.docx",
    nomenclatura: "ЧР-09",
    size: 21705,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-6-1",
    catalogCode: "2.6.1",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Предложение за научно жури от катедрата — доц. / проф.",
    titleEn: "Department proposal for jury — assoc. / prof.",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.6.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.6.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1vEh1Qr00kqC0TJo10p8lAxQPtQKQ16vO",
    sourceFolder: "documents",
    originalTitle: "Образец 2.6.1-1 доклад-предложение за НЖ от катедрата за провеждане на конкурси за доцент_професор.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/documents/p-2-6-1.doc",
    nomenclatura: "ЧР-09",
    size: 32768,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-6-2",
    catalogCode: "2.6.2",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Разширяване състава на ФС/НС за избор на професор",
    titleEn: "Expand faculty/scientific council for professor election",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.6.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.6.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "1LunijB5lHygCiAtqkgH97-E3sZlYgvOr",
    sourceFolder: "documents",
    originalTitle: "Образец 2.6.2. доклад и заповед за разширяване състава на ФС-НС за избор на професор.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-6-2.docx",
    nomenclatura: "ЧР-09",
    size: 19443,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-6-3",
    catalogCode: "2.6.3",
    hub: "career",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация за конфликт на интереси — конкурс доц. / проф.",
    titleEn: "Conflict-of-interest declaration — assoc. / prof. contest",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.6.3. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.6.3. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "1jGY31F7A1hExOF_pB9hWTi6yf71wPPvb",
    sourceFolder: "documents",
    originalTitle: "Образец 2.6.3. декларация за конфликт на интереси-конкурс за доцент_професор.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-6-3.docx",
    nomenclatura: "ЧР-09",
    size: 20139,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-6-4",
    catalogCode: "2.6.4",
    hub: "career",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация за мин. нац. изисквания — жури доц. / проф.",
    titleEn: "Min. national requirements declaration — assoc. / prof. jury",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.6.4. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.6.4. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,program_admin",
    driveFileId: "10nWWr3-vfnBROpYChGhilguFV6cqnjyP",
    sourceFolder: "documents",
    originalTitle: "Образец 2.6.4. декларация за мин.нац. изискв. на членовете на НЖ_конкурси за доцент_професор.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-6-4.docx",
    nomenclatura: "ЧР-09",
    size: 17341,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-7",
    catalogCode: "2.7",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Назначаване на академична длъжност — асистент",
    titleEn: "Appoint academic position — assistant",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.7. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.7. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1iOa8B7GQ6xmgSe5XS9yaEI8rxizlzfXx",
    sourceFolder: "documents",
    originalTitle: "Obrazec-2.7. -doklad naznachvane asistent.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-7.docx",
    nomenclatura: "ЧР-09",
    size: 19528,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-7-1",
    catalogCode: "2.7.1",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Назначаване на академична длъжност — главен асистент",
    titleEn: "Appoint academic position — chief assistant",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.7.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.7.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1yHCEjDrpXhyMfuTnbo3VfZwK2kpqqxb6",
    sourceFolder: "documents",
    originalTitle: "Образец 2.7.1. доклад за назначаване на академична длъжност главен асистент.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-7-1.docx",
    nomenclatura: "ЧР-09",
    size: 19860,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-8",
    catalogCode: "2.8",
    hub: "career",
    family: "contest",
    wizardKind: "dynamic",
    titleBg: "Назначаване на академична длъжност — доцент / професор",
    titleEn: "Appoint academic position — associate / professor",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.8. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.8. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1as4Ka7JReSJsskEWmp8gJCXn_ZrOFpSL",
    sourceFolder: "documents",
    originalTitle: "Obrazec-2.8. -doklad za naznachavane na ak dlazhnost dotsent prof-new.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-8.docx",
    nomenclatura: "ЧР-09",
    size: 19943,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "load-pay-5-2",
    catalogCode: "5.2",
    hub: "load",
    family: "load",
    wizardKind: "load-5-2",
    titleBg: "Натовареност / хонорари — хонорувани преподаватели",
    titleEn: "Load / honorary pay — honorary lecturers",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "12PFiP5OBClZNDKxqG_GHHgsbGUcYlZi8",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.2-doklad izplachtane na vaznagrajdenia honuravani-nov.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/load-pay-5-2.doc",
    nomenclatura: "ФД-23",
    size: 80896,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-5-2a",
    catalogCode: "5.2A",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Договор с хоноруван преподавател (възмезден)",
    titleEn: "Honorary lecturer contract (paid)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.2A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.2A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1kdPHnysUGuXmPBYo9s7id8LWE3cDV1Uw",
    sourceFolder: "HR",
    originalTitle: "5.2A-Договор_хонорувани-Възмезден-2.09.2018_R1.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/HR/p-5-2a.docx",
    nomenclatura: "ФД-23",
    size: 25685,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-5",
    catalogCode: "5.5",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Часове над годишния норматив (КТД)",
    titleEn: "Hours over annual norm (collective agreement)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.5. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.5. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1rGpApSY90Kes9HRWO3uDcxZZiSCmKHzS",
    sourceFolder: "HR",
    originalTitle: "обр. 5.5 - доклад и заповед за изплащане на часове над норматива.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-5.doc",
    nomenclatura: "ФД-23",
    size: 64512,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-6",
    catalogCode: "5.6",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Заповед — допълнителни възнаграждения магистърски програми",
    titleEn: "Order — extra pay for master's programmes",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.6. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.6. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1Y8cK6nDfvUUql2qFby-HIv8EnLemfJTz",
    sourceFolder: "HR",
    originalTitle: "Obrazec 5.6 zapoved.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-6.doc",
    nomenclatura: "ФД-23",
    size: 49152,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-6a",
    catalogCode: "5.6A",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Таблица 5.6.А — доп. възнаграждения МП (EUR)",
    titleEn: "Sheet 5.6.A — master's extra pay (EUR)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.6A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.6A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1dm_oXOyEpIKVQH9knM26eEcafVOzY2OA",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.6.A--dopalnitelni vaznagrajdenia magistarski programi-EUR.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    templateRel: "templates/official/HR/p-5-6a.xlsx",
    nomenclatura: "ФД-23",
    size: 23217,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-5-9",
    catalogCode: "5.9",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Изплащане на базови учители",
    titleEn: "Pay base-school teachers",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.9. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.9. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1Q4CbUkCmcxV0hdiarYOCMnFWSq_7FOy2",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.9-doklad izplachtane vaznagrajdenie bazovi.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-9.doc",
    nomenclatura: "ФД-23",
    size: 60416,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-5-9a",
    catalogCode: "5.9A",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "Справка за часове на базови учители",
    titleEn: "Hour log for base-school teachers",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.9A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.9A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1zrAPxZkJcK3GmvuPIFVixxqLPp3I8tOA",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.9.A-spravka bazovi uchiteli.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-9a.doc",
    nomenclatura: "ФД-23",
    size: 58368,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-5-mp",
    catalogCode: "5.MP",
    hub: "load",
    family: "load",
    wizardKind: "dynamic-load",
    titleBg: "План-сметка на магистърска програма (EUR)",
    titleEn: "Master's programme budget (EUR)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.MP. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.MP. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1S2ALK6xzBLIKGae9ki9DPllD3GLPIkV5",
    sourceFolder: "HR",
    originalTitle: "Образец на план-сметка на МП в евро.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    templateRel: "templates/official/HR/p-5-mp.xlsx",
    nomenclatura: "ФД-23",
    size: 293769,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-5-1",
    catalogCode: "5.1",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Граждански договор + декларация ЗДДФЛ",
    titleEn: "Civil contract + PIT declaration",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "10W2JDpCSeWqxw8ejtggFW5Nn8rl6iWZC",
    sourceFolder: "HR",
    originalTitle: "5.1-doklad i deklaracia-new.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-1.doc",
    nomenclatura: "ПО-03",
    size: 73216,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-11",
    catalogCode: "5.11",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Иницииране на граждански договор с чужденци",
    titleEn: "Initiate civil contract with foreigners",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.11. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.11. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1EbG6flQNeUMNQ22sKK4R_jwGnygN0CY3",
    sourceFolder: "HR",
    originalTitle: "5.11-doklad-iniciirane-gr.dogovor-chujdenci.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-11.doc",
    nomenclatura: "ПО-03",
    size: 36352,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-11a",
    catalogCode: "5.11A",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Service agreement (BG–EN) — general",
    titleEn: "Service agreement (BG–EN) — general",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.11A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.11A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1may8f6AbBuAgXSJ3Cun4anDVObNIBxvr",
    sourceFolder: "HR",
    originalTitle: "5.11A_BG_EN_Service agreement_general.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-11a.doc",
    nomenclatura: "ПО-03",
    size: 55808,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-5-11b",
    catalogCode: "5.11B",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Service agreement (BG–EN) — гост-преподаватели",
    titleEn: "Service agreement (BG–EN) — guest lecturers",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.11B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.11B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "17BnSAE1WeAhnvz2j1mos8nOJqFxxeiPe",
    sourceFolder: "HR",
    originalTitle: "5.11B_BG_EN_Service agreement_Gost-prepodavateli.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/HR/p-5-11b.docx",
    nomenclatura: "ПО-03",
    size: 26079,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-5-11c",
    catalogCode: "5.11C",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Service agreement (BG–EN) — работни програми",
    titleEn: "Service agreement (BG–EN) — work programmes",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.11C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.11C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1H2CqC2Ldxo0j7T9TcHdEY_21LhsI85Pp",
    sourceFolder: "HR",
    originalTitle: "5.11C_BG_EN_Service agreement_Rabotni programi.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-11c.doc",
    nomenclatura: "ПО-03",
    size: 54784,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-5-12",
    catalogCode: "5.12",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Плащане по граждански договор с чужденци",
    titleEn: "Pay foreign civil contract",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.12. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.12. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1cUb9Vxb6PEwCun_qm-i-8xLnlDKIDFnF",
    sourceFolder: "HR",
    originalTitle: "5.12-doklad-plashtane-gr.dogovor-chujdenci.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-12.doc",
    nomenclatura: "ПО-03",
    size: 34816,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-13",
    catalogCode: "5.13",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Бланка гост-преподавател т. 7.1 — по тарифа",
    titleEn: "Guest lecturer form 7.1 — tariff",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.13. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.13. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "11mPzcxGknoUqim5vYRED3N0UH7qMIEPS",
    sourceFolder: "HR",
    originalTitle: "Образец 5.13 - бланка_гост-преподавател по т. 7.1. по тарифа съгл. заповед № РД-19-273 от 14.09.16 и РД 19-40 от 21.01.26.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-13.doc",
    nomenclatura: "ПО-03",
    size: 50688,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-14",
    catalogCode: "5.14",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Бланка гост-преподавател т. 7.2 — цялостно обучение",
    titleEn: "Guest lecturer form 7.2 — full programme",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.14. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.14. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1jlUI2fa5ATVXEPpF3nNulM1pnvYfYeDs",
    sourceFolder: "HR",
    originalTitle: "Образец 5.14 - бланка_гост-преподавател по т. 7.2 за цялостно обучение.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-14.doc",
    nomenclatura: "ПО-03",
    size: 51200,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-5-15",
    catalogCode: "5.15",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Бланка гост-преподавател т. 7.3 — безвъзмездно",
    titleEn: "Guest lecturer form 7.3 — unpaid",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.15. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.15. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1nnb5XMaetWhls0pmMCj4-1ITj7lpdo0l",
    sourceFolder: "HR",
    originalTitle: "5.15. бланка_гост-преподавател по т. 7.3. - безвъзмездно.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-15.doc",
    nomenclatura: "ПО-03",
    size: 47616,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-5-16a",
    catalogCode: "5.16A",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Възлагане на извънреден труд",
    titleEn: "Assign overtime",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.16A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.16A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1JKOQ_MUK93fYdeayO-YqXnRD6-Irs_4M",
    sourceFolder: "HR",
    originalTitle: "обр. 5.16 A – заповед за възлагане на извънреден труд.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/HR/p-5-16a.docx",
    nomenclatura: "ПО-03",
    size: 22338,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-16b",
    catalogCode: "5.16B",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Изплащане на извънреден труд",
    titleEn: "Pay overtime",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.16B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.16B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1zu6xtPhJznwtZsYPP1r2HPk1pFPXah2C",
    sourceFolder: "HR",
    originalTitle: "обр. 5.16 B – заповед за изплащане на извънреден труд.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-16b.doc",
    nomenclatura: "ПО-03",
    size: 70144,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-16c",
    catalogCode: "5.16C",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Изплащане на нощен труд",
    titleEn: "Pay night work",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.16C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.16C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1FUpYhERMAFe5C3ATgL-M7wcQT0g4Dwrh",
    sourceFolder: "HR",
    originalTitle: "обр. 5.16 C – заповед за изплащане на нощен труд.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-16c.doc",
    nomenclatura: "ПО-03",
    size: 58368,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-17b",
    catalogCode: "5.17B",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Изплащане при бюджетни остатъци (чл. 27 ВПРЗ)",
    titleEn: "Pay from residual budget (art. 27)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.17B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.17B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1tFqVeuYVxkI_9kXeZgNPj91AMM8ynLsK",
    sourceFolder: "HR",
    originalTitle: "обр. 5.17 B – заповед за изплащане на възнаграждения при наличие на бюджетни остатъци съгл. чл. 27 ВПРЗ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-17b.doc",
    nomenclatura: "ПО-03",
    size: 53760,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-17c",
    catalogCode: "5.17C",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Доп. възнаграждение на инспектори (чл. 29 / 29а ВПРЗ)",
    titleEn: "Extra pay for inspectors (art. 29 / 29a)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.17C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.17C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1d6-yHlUqQJP6lyzABnUpLj7X81K9SZmt",
    sourceFolder: "HR",
    originalTitle: "обр. 5.17 C–заповед изплащане допълнителни възнаграждения на инспектори и гл. инспектори за увеличен обем работа съгл. чл. 29 и чл. 29а ВПРЗ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-17c.doc",
    nomenclatura: "ПО-03",
    size: 41984,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-17d",
    catalogCode: "5.17D",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Заповед — научни публикации",
    titleEn: "Order — scientific publications",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.17D. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.17D. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1AlAzYLHMjz6jksrCBb2tckRbEogGPmS4",
    sourceFolder: "HR",
    originalTitle: "Заповед научни публикации-образец 5.17 D.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-17d.doc",
    nomenclatura: "ПО-03",
    size: 57856,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-17e",
    catalogCode: "5.17E",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор — научни публикации",
    titleEn: "Contract — scientific publications",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.17E. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.17E. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1WE59zGuBDPrqjpOvgPQvnTDyNgJrogbf",
    sourceFolder: "HR",
    originalTitle: "Договори научни публикации-образец 5.17 E.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-17e.doc",
    nomenclatura: "ПО-03",
    size: 70144,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-1d",
    catalogCode: "5.1D",
    hub: "contracts",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация ЗДДФЛ / самоосигуряващо се лице",
    titleEn: "PIT / self-insured person declaration",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.1D. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.1D. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1I884f9ouB6KqhDKp_DGGiG1fKsyyYmD7",
    sourceFolder: "HR",
    originalTitle: "ДЕКЛАРАЦИЯ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-1d.doc",
    nomenclatura: "ПО-03",
    size: 27648,
    hasPayment: true,
    hasLegal: false,
  },
  {
    slug: "p-5-3a",
    catalogCode: "5.3A",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Възлагане по научен проект (чл. 31)",
    titleEn: "Assign work on a research project (art. 31)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.3A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.3A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "11qYVWomV-FWofbkf9RVx8jm-44_XcYZU",
    sourceFolder: "HR",
    originalTitle: "5.3 A доклад и заповед за възлагане по чл. 31.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-3a.doc",
    nomenclatura: "ПО-03",
    size: 48640,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-3b",
    catalogCode: "5.3B",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Изплащане — вътрешни по чл. 31 ал. 5",
    titleEn: "Pay internals — art. 31(5)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.3B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.3B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1VuhEuQodHMhonL-YFyAOXg7dVhueuHAr",
    sourceFolder: "HR",
    originalTitle: "5.3 B - доклад и заповед за изплащане - вътрешни чл. 31, ал. 5.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-3b.doc",
    nomenclatura: "ПО-03",
    size: 49664,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-3c",
    catalogCode: "5.3C",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор с консултанти по научен проект",
    titleEn: "Contract with project consultants",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.3C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.3C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1sSLS2W_2yzpes4Ln0MkBH5pqMYjtUfhx",
    sourceFolder: "HR",
    originalTitle: "5.3 C - доклад и договор за сключване - научни проекти консултанти.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-3c.doc",
    nomenclatura: "ПО-03",
    size: 60928,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-3ca",
    catalogCode: "5.3CA",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор с членове на научния колектив",
    titleEn: "Contract with project team members",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.3CA. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.3CA. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1VMKTlYNogLh7dZmeWyblypaAceU5xFNq",
    sourceFolder: "HR",
    originalTitle: "5.3 Cа - доклад и договор за сключване - научни проекти - членове на научния колектив на проект.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-3ca.doc",
    nomenclatura: "ПО-03",
    size: 60928,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-3d",
    catalogCode: "5.3D",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Изплащане по научен проект + приемо-предавателен протокол",
    titleEn: "Project pay + handover protocol",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.3D. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.3D. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1qeF-rQ8imA2Y6cZ58hzi-FfP7CIlTNdK",
    sourceFolder: "HR",
    originalTitle: "5.3 D - доклад за изплащане - научни проекти и приемо-предавателен протокол.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-3d.doc",
    nomenclatura: "ПО-03",
    size: 41984,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-4a",
    catalogCode: "5.4A",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Възлагане на допълнителни задачи (чл. 25 ВПРЗ)",
    titleEn: "Assign extra university tasks (art. 25)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.4A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.4A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1LRrUTTyxPR6O9PC8TjwjJ9L_eARyAcQC",
    sourceFolder: "HR",
    originalTitle: "Obrazec 5.4.A.Doklad i zapoved za vazlagane 25 VPRZ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-4a.doc",
    nomenclatura: "ПО-03",
    size: 47104,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-4b",
    catalogCode: "5.4B",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Изплащане по чл. 25 ВПРЗ",
    titleEn: "Pay extra tasks (art. 25)",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.4B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.4B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "19MmOWzifGGg81vNgjmqVehQy_0nPTW4W",
    sourceFolder: "HR",
    originalTitle: "Obrazec 5.4.B.Doklad i zapoved za izplashtane po 25 VPRZ.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-4b.doc",
    nomenclatura: "ПО-03",
    size: 48640,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-7",
    catalogCode: "5.7",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Възнаграждение за кандидат-студентска кампания",
    titleEn: "Pay for admissions campaign",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.7. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.7. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1VFbLwcN6D_ipGfWVkWlatvfgpOLn2g-R",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.7-doklad vaznagragdenie KSK(1).doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-7.doc",
    nomenclatura: "ПО-03",
    size: 38912,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-7a",
    catalogCode: "5.7A",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор с проверител (КСК)",
    titleEn: "Contract with admissions examiner",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.7A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.7A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1F5CZi_jl5bGOerTUl1MfmRM8ODfd323M",
    sourceFolder: "HR",
    originalTitle: "Obrazec 5.7А dogovor-proveritel.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-7a.doc",
    nomenclatura: "ПО-03",
    size: 41472,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-8",
    catalogCode: "5.8",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Договор за базова практика",
    titleEn: "Base-school practical-training contract",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.8. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.8. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1iKa-UOCaReia_15g5xgOW2ycw0IdsLxk",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.8.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-8.doc",
    nomenclatura: "ПО-03",
    size: 86528,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-5-8a",
    catalogCode: "5.8A",
    hub: "contracts",
    family: "contract",
    wizardKind: "dynamic",
    titleBg: "Приложение / договор 5.8А — базова практика",
    titleEn: "Annex 5.8A — base-school practice",
    descriptionBg: "Официална бланка от Drive (HR). Каталожен код: 5.8A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (HR). Catalog code: 5.8A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1CWFyLq9ns_uWPLSB2XMNMsmGun0E5lg_",
    sourceFolder: "HR",
    originalTitle: "Obrazec-5.8A.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/HR/p-5-8a.doc",
    nomenclatura: "ПО-03",
    size: 56832,
    hasPayment: true,
    hasLegal: true,
  },
  {
    slug: "p-2-10",
    catalogCode: "2.10",
    hub: "mywork",
    family: "leave",
    wizardKind: "dynamic",
    titleBg: "Заявление за творчески отпуск",
    titleEn: "Creative leave application",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.10. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.10. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,program_admin,faculty_admin,admin_staff",
    driveFileId: "1CoWzZF6hnLIykHm98carJNj_aPQu7cUT",
    sourceFolder: "documents",
    originalTitle: "творчески отпуск.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-10.docx",
    nomenclatura: "ЧР-01",
    size: 23741,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-2-11",
    catalogCode: "2.11",
    hub: "mywork",
    family: "leave",
    wizardKind: "dynamic",
    titleBg: "Прекъсване на отпуск",
    titleEn: "Interrupt leave",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.11. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.11. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,program_admin,faculty_admin,admin_staff",
    driveFileId: "1gDrLFQNv93w-t3-0zdTEfHvZZ6lciuJm",
    sourceFolder: "documents",
    originalTitle: "прекъсване отпуск.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-11.docx",
    nomenclatura: "ЧР-01",
    size: 17020,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-2-12",
    catalogCode: "2.12",
    hub: "mywork",
    family: "hire",
    wizardKind: "dynamic",
    titleBg: "Заявление за назначаване",
    titleEn: "Hire application",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.12. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.12. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1K9ooGr5cP3ds2J7xJw3yhVdwKp8Uh53N",
    sourceFolder: "documents",
    originalTitle: "заявление назначаване.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/documents/p-2-12.doc",
    nomenclatura: "ЧР-01",
    size: 43520,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-12a",
    catalogCode: "2.12A",
    hub: "mywork",
    family: "declaration",
    wizardKind: "dynamic",
    titleBg: "Декларация при постъпване на работа",
    titleEn: "Incoming-employee declaration",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.12A. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.12A. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,faculty_admin,admin_staff",
    driveFileId: "19zCj3Nm_iWrLNwhQAG1e-mrKdMYMi4aw",
    sourceFolder: "documents",
    originalTitle: "декларация постъпване.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-12a.docx",
    nomenclatura: "ЧР-01",
    size: 21648,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-2-12b",
    catalogCode: "2.12B",
    hub: "mywork",
    family: "hire",
    wizardKind: "dynamic",
    titleBg: "Заявление за преназначаване",
    titleEn: "Reassignment application",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.12B. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.12B. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "12f-koWZyCITDTkJVTxgs9kVSzXnCh6g-",
    sourceFolder: "documents",
    originalTitle: "заявление преназначаване.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-12b.docx",
    nomenclatura: "ЧР-01",
    size: 23518,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-12c",
    catalogCode: "2.12C",
    hub: "mywork",
    family: "hire",
    wizardKind: "dynamic",
    titleBg: "Заявление за продължаване срока на трудов договор",
    titleEn: "Extend employment contract",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.12C. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.12C. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin",
    driveFileId: "1cgG1UbCuELQeOxf7z1OgEHRuAr4_looW",
    sourceFolder: "documents",
    originalTitle: "заявление за продължаване срока на трудов договор.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-12c.docx",
    nomenclatura: "ЧР-01",
    size: 18891,
    hasPayment: false,
    hasLegal: true,
  },
  {
    slug: "p-2-9",
    catalogCode: "2.9",
    hub: "mywork",
    family: "leave",
    wizardKind: "dynamic",
    titleBg: "Заявление за отпуск",
    titleEn: "Leave application",
    descriptionBg: "Официална бланка от Drive (documents). Каталожен код: 2.9. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (documents). Catalog code: 2.9. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "lecturer,program_admin,faculty_admin,admin_staff",
    driveFileId: "1IsH9MqczNk8ZODHCSfm_bRxfBFfL7rmU",
    sourceFolder: "documents",
    originalTitle: "отпуск.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/documents/p-2-9.docx",
    nomenclatura: "ЧР-01",
    size: 21712,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-9-1",
    catalogCode: "9.1",
    hub: "letters",
    family: "letter",
    wizardKind: "dynamic",
    titleBg: "Изходящо писмо до друга институция",
    titleEn: "Outgoing letter to another institution",
    descriptionBg: "Официална бланка от Drive (letters). Каталожен код: 9.1. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (letters). Catalog code: 9.1. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin,admin_staff",
    driveFileId: "1guK-Jn3kdn5Vubyvs9BB7Ovf8N6DFkzp",
    sourceFolder: "letters",
    originalTitle: "Obrazec-9.1-Izhodiachto pismo druga institucia.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/letters/p-9-1.doc",
    nomenclatura: "РД-31",
    size: 772096,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-9-2",
    catalogCode: "9.2",
    hub: "letters",
    family: "letter",
    wizardKind: "dynamic",
    titleBg: "Писмо по вътрешна поща",
    titleEn: "Internal mail",
    descriptionBg: "Официална бланка от Drive (letters). Каталожен код: 9.2. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (letters). Catalog code: 9.2. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin,admin_staff",
    driveFileId: "1ZCQ_THzFvUI8i37-2aVdCJ5UD-GxI0UD",
    sourceFolder: "letters",
    originalTitle: "Obrazec-9.2-Pismo vatrechna pochta.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/letters/p-9-2.docx",
    nomenclatura: "РД-31",
    size: 15000,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-9-3",
    catalogCode: "9.3",
    hub: "letters",
    family: "letter",
    wizardKind: "dynamic",
    titleBg: "Изходящо писмо-отговор",
    titleEn: "Outgoing reply letter",
    descriptionBg: "Официална бланка от Drive (letters). Каталожен код: 9.3. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (letters). Catalog code: 9.3. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin,admin_staff",
    driveFileId: "17ROpi5V2Nh1jknY8AqUIY9HD8mE7Mj5f",
    sourceFolder: "letters",
    originalTitle: "Obrazec-9.3-izhodiachto pismo otgovor.doc",
    mimeType: "application/msword",
    templateRel: "templates/official/letters/p-9-3.doc",
    nomenclatura: "РД-31",
    size: 771072,
    hasPayment: false,
    hasLegal: false,
  },
  {
    slug: "p-9-4",
    catalogCode: "9.4",
    hub: "letters",
    family: "letter",
    wizardKind: "dynamic",
    titleBg: "Докладна записка",
    titleEn: "Official memo (dokladna zapiska)",
    descriptionBg: "Официална бланка от Drive (letters). Каталожен код: 9.4. Официалният шаблон не се променя — порталът попълва данните.",
    descriptionEn: "Official Drive blank (letters). Catalog code: 9.4. Template stays unchanged; the portal fills the data.",
    rolesAllowed: "program_admin,faculty_admin,admin_staff",
    driveFileId: "1__6wwAW0pi7B-BbSW4epXsK82UT9u8DY",
    sourceFolder: "letters",
    originalTitle: "Obrazec-9.4-dokladna zapiska.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    templateRel: "templates/official/letters/p-9-4.docx",
    nomenclatura: "РД-31",
    size: 12833,
    hasPayment: false,
    hasLegal: false,
  },
];

export const HANDBOOK: HandbookItem[] = [
  {
    slug: "roles",
    kind: "roles",
    titleBg: "Роли и системи (Roles.docx)",
    titleEn: "Roles and systems (Roles.docx)",
    summaryBg: "Слоеве: университет / факултет / програма / преподавател / студент. Болката при 5.x хонорари.",
    summaryEn: "Layers: university / faculty / program / lecturer / student. The 5.x honorary-pay pain.",
    driveFileId: "1162OJKtWJM8rYnVqd1PaW6uTDrr9OPYf",
    sourceFolder: "root",
    originalTitle: "Roles.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 18604,
  },
  {
    slug: "most-used-documents",
    kind: "catalog",
    titleBg: "Най-използвани документи (каталог маршрути)",
    titleEn: "Most used documents (routing catalog)",
    summaryBg: "37-страничен каталог (Приложение №1 към инструкцията): раздели 1–9, задължителни полета и маршрут за всяка бланка. Не е бланка — справочник.",
    summaryEn: "37-page catalog (Annex 1): sections 1–9, required fields and route per blank. Knowledge, not a form.",
    driveFileId: "1nSzuy3Q1q246cTS4HnE1EUlpae64MsdR",
    sourceFolder: "root",
    originalTitle: "most used documents.pdf",
    mimeType: "application/pdf",
    size: 2103168,
  },
  {
    slug: "nomenklatura",
    kind: "nomenclatura",
    titleBg: "Номенклатура на делата",
    titleEn: "Records nomenclatura",
    summaryBg: "52 стр. (Ректор 17.03.2021): 17 архивни раздела — РД, УД, ДДСК, ФД, ЧР… Предлага индекс при приключване на преписка.",
    summaryEn: "52 pp. (Rector 17.03.2021): 17 archival sections. Suggest a file index when a case closes.",
    driveFileId: "169ywBDdIVHpW1GfAnAb_HuuBPAi6le0U",
    sourceFolder: "root",
    originalTitle: "Nomenklatura.pdf",
    mimeType: "application/pdf",
    size: 1392352,
  },
  {
    slug: "admin-instruction",
    kind: "instruction",
    titleBg: "Инструкция за административните дейности",
    titleEn: "Instruction for administrative tasks",
    summaryBg: "АС 29.03.2017 (изм. 2019). Деловодство, Архимед, резолюции, печати, срокове (7 дни).",
    summaryEn: "AS 29.03.2017 (amd. 2019). Registry, Arhimed, resolutions, seals, 7-day default deadline.",
    driveFileId: "1tZg0-4uktc2i0E3J4o2J29jSyYTaT6Uo",
    sourceFolder: "root",
    originalTitle: "instructions for the administrative tasks.pdf",
    mimeType: "application/pdf",
    size: 270790,
  },
  {
    slug: "uchplan-afrikanistika",
    kind: "curriculum",
    titleBg: "Учебен план — Африканистика (KNA240425)",
    titleEn: "Curriculum — African Studies (KNA240425)",
    summaryBg: "БА, поле 2.1, 8 семестъра, випуск 2025/26. 2310 ч / 186 ECTS задължителни + 600 ч / 44 ECTS избираеми.",
    summaryEn: "BA, field 2.1, 8 semesters, 2025/26. 2310 h / 186 ECTS required + 600 h / 44 ECTS electives.",
    driveFileId: "1rkl2d8ViQmhPKQ8Yiju2M802iJaeoMot",
    sourceFolder: "root",
    originalTitle: "UchPlan.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 110745,
  },
];


const f = (
  name: string,
  labelBg: string,
  labelEn: string,
  type: FieldType = "text",
  required = true,
  options?: CatalogField["options"]
): CatalogField => ({ name, labelBg, labelEn, type, required, options });

const COMMON_PERSON: CatalogField[] = [
  f("fullName", "Име и фамилия", "Full name"),
  f("egn", "ЕГН / ЛНЧ", "Personal ID", "text", false),
  f("faculty", "Факултет", "Faculty"),
  f("department", "Катедра / програма", "Department / programme"),
];

const DATES: CatalogField[] = [
  f("dateFrom", "От дата", "From date", "date"),
  f("dateTo", "До дата", "To date", "date"),
];

const GROUNDS = f("grounds", "Основание / мотиви", "Grounds / motivation", "textarea");
const AMOUNT = f("amount", "Сума", "Amount", "number", false);
const IBAN = f("iban", "IBAN", "IBAN", "iban", false);
const FUNDING = f("fundingSource", "Източник на средства", "Source of funds");
const PERIOD = f("period", "Период", "Period");
const SUBJECT = f("subject", "Относно", "Subject");

export function fieldsFor(p: CatalogProcess): CatalogField[] {
  const extra: CatalogField[] = [];
  switch (p.family) {
    case "petition":
      extra.push(
        f("studentId", "Факултетен номер", "Student ID"),
        f("year", "Курс / година", "Year of study", "text", false),
        f("specialty", "Специалност", "Specialty"),
        ...DATES.map((x) => ({ ...x, required: false })),
        GROUNDS
      );
      if (p.catalogCode === "3.7" || p.hasPayment) extra.push(IBAN, AMOUNT, FUNDING);
      if (p.catalogCode === "3.5") {
        extra.push(
          f("pudGround", "Основание по ПУД чл. 165", "PUD art. 165 ground", "select", true, [
            { value: "illness", labelBg: "Заболяване", labelEn: "Illness" },
            { value: "childbirth", labelBg: "Раждане / отглеждане", labelEn: "Childbirth / childcare" },
            { value: "exams", labelBg: "Неположени изпити", labelEn: "Failed / pending exams" },
            { value: "abroad", labelBg: "Частично обучение в чужбина", labelEn: "Partial study abroad" },
            { value: "other", labelBg: "Друго", labelEn: "Other" },
          ])
        );
      }
      break;
    case "leave":
      extra.push(
        f("position", "Длъжност", "Position", "text", false),
        f("leaveType", "Вид отпуск", "Leave type", "select", true, [
          { value: "paid", labelBg: "Платен годишен", labelEn: "Paid annual" },
          { value: "unpaid", labelBg: "Неплатен", labelEn: "Unpaid" },
          { value: "creative", labelBg: "Творчески", labelEn: "Creative" },
          { value: "other", labelBg: "Друг", labelEn: "Other" },
        ]),
        ...DATES,
        GROUNDS,
        f("has110", "Имам договор по чл. 110 КТ (втори)", "I have a dual art. 110 contract", "checkbox", false)
      );
      break;
    case "hire":
      extra.push(
        f("position", "Длъжност", "Position"),
        ...DATES.map((x) => ({ ...x, required: false })),
        GROUNDS
      );
      break;
    case "declaration":
      extra.push(
        f("roleInCase", "Роля (член на жури / кандидат / служител)", "Role (jury / candidate / staff)"),
        f("contestOrFile", "Конкурс / преписка", "Contest / case", "text", false),
        f("declareTrue", "Декларирам верността на данните", "I declare the data is true", "checkbox"),
        GROUNDS
      );
      break;
    case "letter":
      extra.push(
        f("addressee", "Адресат", "Addressee"),
        f("addresseeTitle", "Длъжност на адресата", "Addressee title", "text", false),
        SUBJECT,
        f("yourRef", "На Ваш №", "Your ref. no.", "text", false),
        f("body", "Текст", "Body", "textarea"),
        f("attachments", "Приложения", "Attachments", "textarea", false)
      );
      break;
    case "load":
      extra.push(
        PERIOD,
        f("program", "Програма / специалност", "Programme"),
        FUNDING,
        AMOUNT,
        f("loadLines", "Редове натовареност", "Load lines", "loadLines", false)
      );
      break;
    case "pay":
    case "contract":
      extra.push(
        f("counterparty", "Контрагент / лице", "Counterparty / person", "text", false),
        PERIOD,
        FUNDING,
        AMOUNT,
        IBAN,
        GROUNDS
      );
      break;
    case "contest":
      extra.push(
        f("position", "Академична длъжност", "Academic position"),
        f("professionalField", "Професионално направление", "Professional field"),
        f("dvCitation", "ДВ / ежедневник (цитат)", "State Gazette / press citation", "text", false),
        f("fsExtract", "Протокол / препис-извлечение ФС", "Faculty council extract", "text", false),
        GROUNDS
      );
      break;
    case "phd":
      extra.push(
        f("candidateName", "Име на докторанта / кандидата", "Doctoral candidate name", "text", false),
        f("phdForm", "Форма", "Form", "select", false, [
          { value: "full", labelBg: "Редовна", labelEn: "Full-time" },
          { value: "part", labelBg: "Задочна", labelEn: "Part-time" },
          { value: "independent", labelBg: "Самостоятелна", labelEn: "Independent" },
        ]),
        f("professionalField", "Професионално направление", "Professional field", "text", false),
        f("supervisor", "Научен ръководител", "Supervisor", "text", false),
        GROUNDS
      );
      if (p.hasPayment) extra.push(FUNDING, AMOUNT);
      break;
    default:
      extra.push(PERIOD, GROUNDS);
      if (p.hasPayment) extra.push(FUNDING, AMOUNT, IBAN);
  }
  return [...COMMON_PERSON, ...extra];
}

export function catalogBySlug(slug: string): CatalogProcess | undefined {
  return CATALOG.find((p) => p.slug === slug);
}
